name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: |
          mvn clean package
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Deploy to GitHub Package Registry
        run: mvn --settings settings.xml -Pgithub clean deploy
